name: Build Android APK (Capacitor)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

concurrency:
  group: build-android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i --no-audit --no-fund

      - name: Build web (Vite)
        run: npm run build

      - name: Add Android platform and sync
        run: |
          npx cap add android
          npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew

      - name: Build debug APK
        working-directory: android
        run: ./gradlew --no-daemon assembleDebug

      # Exactly ONE upload step, always-unique name even on re-runs
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.run_id }}-${{ github.run_attempt }}
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew

      - name: Build debug APK
        working-directory: android
        run: ./gradlew --no-daemon assembleDebug

      # ⬇️ Exactly ONE upload step, with a unique name per run and re-run
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.run_id }}-${{ github.run_attempt }}
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew

      - name: Build debug APK
        working-directory: android
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
